sudo: required
language: ruby

before_install:
  - sudo apt-get install enca # not sure why this isn't installed
  - sudo add-apt-repository 'deb http://cran.rstudio.com/bin/linux/ubuntu precise/'
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9
  - sudo add-apt-repository ppa:marutter/rdev -y
  - sudo apt-get update -q
  - sudo apt-get install r-base -y
  - R --version # By default it installs ~2.1
  # Install GCAT R package
  - cd R/GCAT
  # - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
  - ./travis-tool.sh install_deps
  - cd ../
  - sudo R CMD INSTALL GCAT
  - cd ../Rails

r_packages:
  - gplots
  - pheatmaps
